# Generated by Django 2.2 on 2020-06-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
