# Generated by Django 2.2 on 2020-06-17 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_degree_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joblist',
            name='description',
        ),
        migrations.AddField(
            model_name='jobdetail',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.JobList'),
        ),
    ]
